
CREATE TABLE USERS (
    User_Id INT PRIMARY KEY AUTO_INCREMENT,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Username VARCHAR(50) UNIQUE,
    Reg_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) DEFAULT 'active'
);


CREATE TABLE BANK (
    B_ID INT PRIMARY KEY AUTO_INCREMENT,
    B_Name VARCHAR(100) NOT NULL,
    Address VARCHAR(255),
    Ph_no VARCHAR(15)
);


CREATE TABLE BRANCH (
    BR_ID INT PRIMARY KEY AUTO_INCREMENT,
    B_ID INT,
    IFSCODE VARCHAR(20) UNIQUE NOT NULL,
    M_ID INT,
    BR_Name VARCHAR(100),
    Address VARCHAR(255),
    FOREIGN KEY (B_ID) REFERENCES BANK(B_ID) ON DELETE CASCADE
);


CREATE TABLE EMPLOYEE (
    E_ID INT PRIMARY KEY AUTO_INCREMENT,
    B_ID INT,
    Fname VARCHAR(50),
    Minit CHAR(1),
    Lname VARCHAR(50),
    Phone_no VARCHAR(15),
    Address VARCHAR(255),
    Desg VARCHAR(50),
    FOREIGN KEY (B_ID) REFERENCES BANK(B_ID) ON DELETE CASCADE
);


CREATE TABLE CUSTOMERS (
    C_Id INT PRIMARY KEY AUTO_INCREMENT,
    B_Id INT,
    User_Id INT UNIQUE,
    Fname VARCHAR(50),
    Minit CHAR(1),
    Lname VARCHAR(50),
    Address TEXT,
    Ph_no VARCHAR(15),
    FOREIGN KEY (B_Id) REFERENCES BANK(B_Id) ON DELETE CASCADE,
    FOREIGN KEY (User_Id) REFERENCES USERS(User_Id) ON DELETE CASCADE
);

CREATE TABLE ACCOUNT (
    Acc_no INT PRIMARY KEY AUTO_INCREMENT,
    C_ID INT,
    Acc_type VARCHAR(20),
    Bal DECIMAL(15,2),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID) ON DELETE CASCADE
);


CREATE TABLE LOAN (
    L_ID INT PRIMARY KEY AUTO_INCREMENT,
    C_ID INT,
    Loan_type VARCHAR(30),
    Amount DECIMAL(15,2),
    Interest DECIMAL(5,2),
    EMI DECIMAL(10,2),
    S_date DATE,
    E_date DATE,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
    Trans_id INT PRIMARY KEY AUTO_INCREMENT,
    C_ID INT,
    Acc_no INT,
    Trans_type VARCHAR(20),
    Amount DECIMAL(15,2),
    Date DATE,
    Time TIME,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID) ON DELETE CASCADE,
    FOREIGN KEY (Acc_no) REFERENCES ACCOUNT(Acc_no) ON DELETE CASCADE
);

CREATE TABLE HOLDS (
    C_ID INT,
    Acc_no INT,
    PRIMARY KEY (C_ID, Acc_no),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID) ON DELETE CASCADE,
    FOREIGN KEY (Acc_no) REFERENCES ACCOUNT(Acc_no) ON DELETE CASCADE
);

CREATE TABLE TAKES (
    C_ID INT,
    L_ID INT,
    PRIMARY KEY (C_ID, L_ID),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMERS(C_ID) ON DELETE CASCADE,
    FOREIGN KEY (L_ID) REFERENCES LOAN(L_ID) ON DELETE CASCADE
);
